version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:9000:9000"
    restart: always
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=111111
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
  nats-streaming-server:
    container_name: nats-streaming-server
    image: nats-streaming
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8223:8223"
    command: ["-m", "8222", "--store", "file", "--dir", "nats-streaming"]
    restart: always
  nats:
    container_name: nats-server
    image: nats
    ports:
      - "127.0.0.1:4223:4222"
      - "127.0.0.1:6222:6222"
      - "127.0.0.1:8222:8222"
    restart: always
  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - ./minio:/data
    ports:
      - "127.0.0.1:9001:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio20171222
    command: ["server", "/data"]
    restart: always
