CREATE DATABASE IF NOT EXISTS `user`;
USE `user`;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `unionid` VARCHAR(29)  UNIQUE,
  `username` VARCHAR(128),
  `phone` VARCHAR (16),
  `password` VARCHAR(128),
  `sex` INT(8) UNSIGNED,
  `isadmin` BOOLEAN NOT NULL,
  `type` VARCHAR(32),
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastlogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isactive` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;