CREATE DATABASE IF NOT EXISTS `shop`;
USE `shop`;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `unionid` VARCHAR(29)  UNIQUE,
  `username` VARCHAR(128),
  `avatar` VARCHAR(128),
  `phone` VARCHAR (16),
  `password` VARCHAR(128),
  `sex` INT(8) UNSIGNED COMMENT '0:男;1:女',
  `isadmin` BOOLEAN NOT NULL DEFAULT 0,
  `type` VARCHAR(32),
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastlogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isactive` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `phoneuser` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128),
  `phone` VARCHAR (16),
  `password` VARCHAR(128),
  `avatar` VARCHAR(128),
  `sex` INT(8) UNSIGNED,
  `isadmin` BOOLEAN NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `address` (
  `id` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userid` INT(32) UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `phone` VARCHAR (16) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `isdefault` BOOLEAN NOT NULL DEFAULT FALSE,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE IF NOT EXISTS `cart` (
  `id` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(32) UNSIGNED NOT NULL,
  `ware_id` INT(32) UNSIGNED,
  `count` INT(32) UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `collect` (
  `id` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(32) UNSIGNED NOT NULL,
  `ware_id` INT(32) UNSIGNED,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


CREATE TABLE IF NOT EXISTS `category` (
  `id` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR (50) NOT NULL,
  `parent_id` INT(32) UNSIGNED NOT NULL DEFAULT 0,
  `is_active` BOOLEAN NOT NULL DEFAULT FALSE,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `orders` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bill_id` VARCHAR(128),
  `user_id` INT(64),
  `parent_id` INT(64),
  `status` INT(64),
  `ware_id` INT(64),
  `count` INT (32),
  `price` DOUBLE(10, 2),
  `receive_way` INT(8),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `wares` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `desc` VARCHAR(100) NOT NULL,
  `parent_category_id` INT(16) NOT NULL,
  `category_id` INT(16) NOT NULL,
  `total_sale` INT(32),
  `inventory` INT(16),
  `status` INT(8) DEFAULT 1,
  `price` DOUBLE(10, 2),
  `sale_price` DOUBLE(10, 2),
  `avatar` VARCHAR(128),
  `image` VARCHAR(128),
  `detail_pic` VARCHAR(128),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `panels` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `desc` VARCHAR(100) NOT NULL,
  `type` INT(8) NOT NULL DEFAULT 0,
  `status` INT(8) DEFAULT 1,
  `sequence` INT(8) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `details` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `belong` VARCHAR(50) NOT NULL,
  `picture` VARCHAR(100) NOT NULL,
  `content` LONGTEXT,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

