CREATE DATABASE IF NOT EXISTS `shop`;
USE `shop`;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
  `openid` VARCHAR(28)  UNIQUE NOT NULL,
  `unionid` VARCHAR(29)  UNIQUE NOT NULL,
  `username` VARCHAR(128),
  `phone` VARCHAR (16),
  `password` VARCHAR(128),
  `avatar` VARCHAR(128),
  `sex` INT(8) UNSIGNED,
  `isadmin` BOOLEAN NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `address` (
  `id` int(32) unsigned NOT NULL AUTO_INCREMENT,
  `userid` int(32) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `phone` VARCHAR (16) NOT NULL,
  `isdefault` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;